### ISSUE TITLE
extracting page titles

### ISSUE THREAD

**Issue by sreekrishnadutta** [Ironholds/WikipediR#13]
Hi,

I am currently working on a project where I need to extract all pages related to "neutron star" and other terms related to astrophysics. I was able to get to the plinks extraction part.
My question: Is it possible to just extract a specific part of the plink$query? In the output, 
![image](https://cloud.githubusercontent.com/assets/14215874/18614845/7aab100a-7db4-11e6-968f-baf94f85839f.png)
I only need the titles and not the rest, and I need them in a single column for me to go further.

I used page_links function. Please let me know if you need further information.

**Comment by Ironholds** [comment]
Ack, sorry; travelling! Still an issue?

**Comment by sreekrishnadutta** [comment]
No problem at all! I managed to scrape the site manually. I couldn't extract just the results from plinks. Got what I need! Your library is awesome though!
