### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by isomorphisms** [Ironholds/WikipediR#15]
first couple thoughts after reading https://ironholds.org/blog/introducing-wikipedir/

1. where did `wiki_con()` go?
2. second thing I tried was `user_information('my editor name')`, which fails because `user_names` is not the first property. (But I think that would be good UI.)
3. first thing I want to do is grab a random wikipedia page (not literally random, but whichever one first occurred to me). So a convenience wrapper for `encyclopedia_article()` would be good.
4. using one of R's XML parsers (is it `httr` now? `selectorgadget`? Duncan ___'s omega-hat one?) on the output of my test wikipedia page will probably be my next step.

HTH

**Comment by Ironholds** [comment]
1. `wiki_con()` was part of the old API; it went away when the connection information got integrated with individual functions such as `user_info`, which leads nicely into...
2. I get the argument for user_names being the first argument (it makes sense in say, `magrittr` style pipelines) but arguments are ordered by conceptual importance and whether they're mandatory or not, so 'what site do you want to query' goes first.
3. There isn't an `encyclopedia_article` function; do you mean you just want to grab the page content?
4. I imagine it'd be `rvest/xml2`, yeah.
