### ISSUE TITLE
Pull specific properties of an item?

### ISSUE THREAD

**Issue by doctornerdis** [Ironholds/WikipediR#19]
Is there a way to get a property for a specific item? For instance, if I know that author Gabriel García Márquez is item Q5878 and property nationality is P27, is there a way to pull Gabriel García Márquez's nationality? Or cycle through the claims of that item until I get to P27?

**Comment by Ironholds** [comment]
Uh. Is this for WikipediR, or the Wikidata API client?

**Comment by Ironholds** [comment]
@doctornerdis ?

**Comment by doctornerdis** [comment]
Actually, it's for WikidataR. Sorry to post on the wrong repository. But is there a way to do it?

**Comment by Ironholds** [comment]
See https://github.com/Ironholds/WikidataR/issues/22 - it's on the to-do list.
