### ISSUE TITLE
Entity Resolution and Fuzzy Matching

### ISSUE THREAD

**Issue by abresler** [Ironholds/WikipediR#8]
Would love to have functionality to attempt to fuzzy match entity resolution.  As a result of successful output it would be great to share the results with the wikidata community as well, sample example:

I have a data frame with entity names and I see 

```
name.entity <- 
"Wells Fargo Corporate Properties"
name.entity.resolved <-
 "Wells Fargo"

```

Ideally it would be nice to try to infer these or even allow the user to override.

**Comment by Ironholds** [comment]
And you'd get from the first to the second..how?

**Comment by abresler** [comment]
I have the data from the first row, the second is just my knowledge but tools like freebase try to estimate this

**Comment by Ironholds** [comment]
Indeed, but tools like freebase have a server cluster and a group of PhDs behind them - we've got R that has to be performant on a lot of systems. I think this is totally something that Wikidata itself would be interested in working on but I don't think it's a good fit for a client library.

**Comment by abresler** [comment]
Perfect I'll see if I can put that up over there

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​
